import objectAssign from 'object-assign';
import Promise from 'bluebird';

const initialState = {
  pending: false,
  message: "",
  error: ""
};

/* eslint no-unused-vars: "off" */

const SAY_HELLO = 'helloapp/SAY_HELLO';

const SAY_HELLO_ASYNC = 'helloapp/SAY_HELLO_ASYNC';
// these are generated by redux promise resolver
const SAY_HELLO_ASYNC_REQUEST = 'helloapp/SAY_HELLO_ASYNC_REQUEST';
const SAY_HELLO_ASYNC_ERROR = 'helloapp/SAY_HELLO_ASYNC_ERROR';

function asyncHello(msg) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(msg);
    }, 1000);
  });
}

export function sayHello(msg) {
  "@action sayHello";
  return { type: SAY_HELLO, message: msg };
}

export function sayHelloAsync(msg) {
  "@action sayHelloAsync";
  return { type: SAY_HELLO_ASYNC, payload: asyncHello(msg) };
}

export default function reducer(state = initialState, action = {}) {
  let newState;
  switch (action.type) {
    case SAY_HELLO:
      newState = objectAssign({}, {message: action.message});
      return newState;

    case SAY_HELLO_ASYNC_REQUEST:
      newState = objectAssign({}, {message: '', pending: true});
      return newState;

    case SAY_HELLO_ASYNC:
      newState = objectAssign({}, {message: action.payload}, {pending: false});
      return newState;

    case SAY_HELLO_ASYNC_ERROR:
      newState = objectAssign({}, {error: action.error}, {pending: false});
      return newState;

    default:
      return state;
  }
}
